#!/usr/bin/env bash

# Usage info
show_help() {
    cat << EOF
    Usage: ${0##*/} [-f] [REPO] [PACKAGE]
    This script will try to install a locally built perfSONAR [PACKAGE]
    and will be using packages out of perfsonar-[REPO]-snapshot to solve
    dependencies.

    The only [REPO] names being recognised are 'patch' or 'minor' (which is
    anything other than 'patch').

    This script will run some commands with sudo, the current user need to
    be granted access.

    Arguments:
        -f: force installation even if [PACKAGE] is not found locally

    Examples:
        ./ps-install-test minor pscheduler-server
EOF
}

# Initialisations

# Parsing options
while getopts "f" OPT; do
    case $OPT in
        f) force=true ;;
        '?')
            show_help >&2
            exit 1 ;;
    esac
done
shift $((OPTIND-1))

# We need a repository type: minor or patch
if [ $1 ]; then
    REPO=$1
else
    echo "We need a repo name (patch or minor) as second arg."
    echo
    show_help >&2
    exit 1
fi

# And we need to have package full name (without version number)
if [ $2 ]; then
    PKG=$2
else
    echo "We need a package name as first arg."
    echo
    show_help >&2
    exit 1
fi

# Check the package is existing locally or if we force installation
if [ -z $force ] && ! compgen -G "/vagrant/result/${PKG}_*" > /dev/null; then
    echo "I cannot see any $PKG in the local repo at /vagrant/result/"
    exit 1
fi

# Add the perfSONAR snapshot repository
cd /etc/apt/sources.list.d
sudo rm -f perfsonar-minor-snapshot.list
sudo rm -f perfsonar-patch-snapshot.list

if [[ "$REPO" == "patch" ]]; then
    sudo wget http://downloads.perfsonar.net/debian/perfsonar-patch-snapshot.list
else
    sudo wget http://downloads.perfsonar.net/debian/perfsonar-minor-snapshot.list
fi

# Refresh APT info
sudo apt-get update

# Try to do the install
echo -e "I'm now going to try to install the latest version of \033[1;36m$PKG\033[0m solving dependencies with the \033[1;36m$REPO-snapshot\033[0m repository."
# Can also be used with DEBIAN_FRONTEND=noninteractive if you want to avoid the pscheduler-server prompts
sudo apt install $PKG

